### ISSUE TITLE
学习了！

### ISSUE THREAD

**Issue by taksssss** [suzukua/epg#1]
没想到还能这么用！
学习了！
神奇的Actions。

**Comment by suzukua** [comment]
> 没想到还能这么用！ 学习了！ 神奇的Actions。

流程大概是action这样。但是我已经没用了，转coding.net构建了。

感谢作者啊，一直想要聚合epg的，但是不想写代码，哈哈

**Comment by taksssss** [comment]
😂我一开始以为是抽取部分代码。
没想到还能直接部署这么简单粗暴！
太6了哈哈哈。
